<?php

use Illuminate\Database\Seeder;
use App\Model\District;

class DistrictsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        District::create(['name' => 'Meru', 'region_id' => $this->getRegionByName('Arusha')]);
        District::create(['name' => 'Arusha Urban', 'region_id' => $this->getRegionByName('Arusha')]);
        District::create(['name' => 'Arusha Rural', 'region_id' => $this->getRegionByName('Arusha')]);
        District::create(['name' => 'Karatu', 'region_id' => $this->getRegionByName('Arusha')]);
        District::create(['name' => 'Longido', 'region_id' => $this->getRegionByName('Arusha')]);
        District::create(['name' => 'Monduli', 'region_id' => $this->getRegionByName('Arusha')]);
        District::create(['name' => 'Ngorongoro', 'region_id' => $this->getRegionByName('Arusha')]);
        District::create(['name' => 'Ilala', 'region_id' => $this->getRegionByName('Dar es Salaam')]);
        District::create(['name' => 'Kinondoni', 'region_id' => $this->getRegionByName('Dar es Salaam')]);
        District::create(['name' => 'Temeke', 'region_id' => $this->getRegionByName('Dar es Salaam')]);
        District::create(['name' => 'Ubungo', 'region_id' => $this->getRegionByName('Dar es Salaam')]);
        District::create(['name' => 'Kigamboni', 'region_id' => $this->getRegionByName('Dar es Salaam')]);
        District::create(['name' => 'Bahi', 'region_id' => $this->getRegionByName('Dodoma')]);
        District::create(['name' => 'Chamwino', 'region_id' => $this->getRegionByName('Dodoma')]);
        District::create(['name' => 'Chemba', 'region_id' => $this->getRegionByName('Dodoma')]);
        District::create(['name' => 'Dodoma', 'region_id' => $this->getRegionByName('Dodoma')]);
        District::create(['name' => 'Kondoa', 'region_id' => $this->getRegionByName('Dodoma')]);
        District::create(['name' => 'Kongwa', 'region_id' => $this->getRegionByName('Dodoma')]);
        District::create(['name' => 'Mpwapwa', 'region_id' => $this->getRegionByName('Dodoma')]);
        District::create(['name' => 'Bukombe', 'region_id' => $this->getRegionByName('Geita')]);
        District::create(['name' => 'Chato', 'region_id' => $this->getRegionByName('Geita')]);
        District::create(['name' => 'Geita Urban', 'region_id' => $this->getRegionByName('Geita')]);
        District::create(['name' => 'Geita Rural', 'region_id' => $this->getRegionByName('Geita')]);
        District::create(['name' => 'Mbongwe', 'region_id' => $this->getRegionByName('Geita')]);
        District::create(['name' => 'Nyang\'hwale', 'region_id' => $this->getRegionByName('Geita')]);
        District::create(['name' => 'Iringa Rural', 'region_id' => $this->getRegionByName('Iringa')]);
        District::create(['name' => 'Iringa Urban', 'region_id' => $this->getRegionByName('Iringa')]);
        District::create(['name' => 'Kilolo', 'region_id' => $this->getRegionByName('Iringa')]);
        District::create(['name' => 'Mafinga', 'region_id' => $this->getRegionByName('Iringa')]);
        District::create(['name' => 'Mufindi', 'region_id' => $this->getRegionByName('Iringa')]);
        District::create(['name' => 'Biharamulo', 'region_id' => $this->getRegionByName('Kagera')]);
        District::create(['name' => 'Bukoba', 'region_id' => $this->getRegionByName('Kagera')]);
        District::create(['name' => 'Karagwe', 'region_id' => $this->getRegionByName('Kagera')]);
        District::create(['name' => 'Kyerwa', 'region_id' => $this->getRegionByName('Kagera')]);
        District::create(['name' => 'Missenyi', 'region_id' => $this->getRegionByName('Kagera')]);
        District::create(['name' => 'Muleba', 'region_id' => $this->getRegionByName('Kagera')]);
        District::create(['name' => 'Ngara', 'region_id' => $this->getRegionByName('Kagera')]);
        District::create(['name' => 'Micheweni', 'region_id' => $this->getRegionByName('Pemba North')]);
        District::create(['name' => 'Wete', 'region_id' => $this->getRegionByName('Pemba North')]);
        District::create(['name' => 'Kaskazini A', 'region_id' => $this->getRegionByName('Unguja North')]);
        District::create(['name' => 'Kaskazini B', 'region_id' => $this->getRegionByName('Unguja North')]);
        District::create(['name' => 'Mlele', 'region_id' => $this->getRegionByName('Katavi')]);
        District::create(['name' => 'Mpanda', 'region_id' => $this->getRegionByName('Katavi')]);
        District::create(['name' => 'Buhigwe', 'region_id' => $this->getRegionByName('Kigoma')]);
        District::create(['name' => 'Kakonko', 'region_id' => $this->getRegionByName('Kigoma')]);
        District::create(['name' => 'Kasulu', 'region_id' => $this->getRegionByName('Kigoma')]);
        District::create(['name' => 'Kasulu', 'region_id' => $this->getRegionByName('Kigoma')]);
        District::create(['name' => 'Kibondo', 'region_id' => $this->getRegionByName('Kigoma')]);
        District::create(['name' => 'Kigoma', 'region_id' => $this->getRegionByName('Kigoma')]);
        District::create(['name' => 'Kigoma-Ujiji', 'region_id' => $this->getRegionByName('Kigoma')]);
        District::create(['name' => 'Uvinza', 'region_id' => $this->getRegionByName('Kigoma')]);
        District::create(['name' => 'Hai', 'region_id' => $this->getRegionByName('Kilimanjaro')]);
        District::create(['name' => 'Moshi Rural', 'region_id' => $this->getRegionByName('Kilimanjaro')]);
        District::create(['name' => 'Moshi Urban', 'region_id' => $this->getRegionByName('Kilimanjaro')]);
        District::create(['name' => 'Mwanga', 'region_id' => $this->getRegionByName('Kilimanjaro')]);
        District::create(['name' => 'Rombo', 'region_id' => $this->getRegionByName('Kilimanjaro')]);
        District::create(['name' => 'Same', 'region_id' => $this->getRegionByName('Kilimanjaro')]);
        District::create(['name' => 'Siha', 'region_id' => $this->getRegionByName('Kilimanjaro')]);
        District::create(['name' => 'Chake Chake', 'region_id' => $this->getRegionByName('Pemba South')]);
        District::create(['name' => 'Mkoani', 'region_id' => $this->getRegionByName('Pemba South')]);
        District::create(['name' => 'Kati', 'region_id' => $this->getRegionByName('Unguja South')]);
        District::create(['name' => 'Kusini', 'region_id' => $this->getRegionByName('Unguja South')]);
        District::create(['name' => 'Kilwa', 'region_id' => $this->getRegionByName('Lindi')]);
        District::create(['name' => 'Lindi Rural', 'region_id' => $this->getRegionByName('Lindi')]);
        District::create(['name' => 'Lindi Urban', 'region_id' => $this->getRegionByName('Lindi')]);
        District::create(['name' => 'Liwale', 'region_id' => $this->getRegionByName('Lindi')]);
        District::create(['name' => 'Nachingwea', 'region_id' => $this->getRegionByName('Lindi')]);
        District::create(['name' => 'Ruangwa', 'region_id' => $this->getRegionByName('Lindi')]);
        District::create(['name' => 'Babati Urban', 'region_id' => $this->getRegionByName('Manyara')]);
        District::create(['name' => 'Babati Rural', 'region_id' => $this->getRegionByName('Manyara')]);
        District::create(['name' => 'Hanang', 'region_id' => $this->getRegionByName('Manyara')]);
        District::create(['name' => 'Kiteto', 'region_id' => $this->getRegionByName('Manyara')]);
        District::create(['name' => 'Mbulu', 'region_id' => $this->getRegionByName('Manyara')]);
        District::create(['name' => 'Simanjiro', 'region_id' => $this->getRegionByName('Manyara')]);
        District::create(['name' => 'Bunda', 'region_id' => $this->getRegionByName('Mara')]);
        District::create(['name' => 'Butiama', 'region_id' => $this->getRegionByName('Mara')]);
        District::create(['name' => 'Musoma Rural', 'region_id' => $this->getRegionByName('Mara')]);
        District::create(['name' => 'Musoma Urban', 'region_id' => $this->getRegionByName('Mara')]);
        District::create(['name' => 'Rorya', 'region_id' => $this->getRegionByName('Mara')]);
        District::create(['name' => 'Serengeti', 'region_id' => $this->getRegionByName('Mara')]);
        District::create(['name' => 'Tarime', 'region_id' => $this->getRegionByName('Mara')]);
        District::create(['name' => 'Chunya', 'region_id' => $this->getRegionByName('Mbeya')]);
        District::create(['name' => 'Ileje', 'region_id' => $this->getRegionByName('Mbeya')]);
        District::create(['name' => 'Kyela', 'region_id' => $this->getRegionByName('Mbeya')]);
        District::create(['name' => 'Mbarali', 'region_id' => $this->getRegionByName('Mbeya')]);
        District::create(['name' => 'Mbeya Urban', 'region_id' => $this->getRegionByName('Mbeya')]);
        District::create(['name' => 'Mbeya Rural', 'region_id' => $this->getRegionByName('Mbeya')]);
        District::create(['name' => 'Mbozi', 'region_id' => $this->getRegionByName('Mbeya')]);
        District::create(['name' => 'Momba', 'region_id' => $this->getRegionByName('Mbeya')]);
        District::create(['name' => 'Rungwe', 'region_id' => $this->getRegionByName('Mbeya')]);
        District::create(['name' => 'Tunduma', 'region_id' => $this->getRegionByName('Mbeya')]);
        District::create(['name' => 'Magharibi', 'region_id' => $this->getRegionByName('Mjini Magharibi')]);
        District::create(['name' => 'Mjini', 'region_id' => $this->getRegionByName('Mjini Magharibi')]);
        District::create(['name' => 'Gairo', 'region_id' => $this->getRegionByName('Morogoro')]);
        District::create(['name' => 'Kilombero', 'region_id' => $this->getRegionByName('Morogoro')]);
        District::create(['name' => 'Kilosa', 'region_id' => $this->getRegionByName('Morogoro')]);
        District::create(['name' => 'Morogoro Rural', 'region_id' => $this->getRegionByName('Morogoro')]);
        District::create(['name' => 'Morogoro Urban', 'region_id' => $this->getRegionByName('Morogoro')]);
        District::create(['name' => 'Mvomero', 'region_id' => $this->getRegionByName('Morogoro')]);
        District::create(['name' => 'Ulanga', 'region_id' => $this->getRegionByName('Morogoro')]);
        District::create(['name' => 'Masasi Rural', 'region_id' => $this->getRegionByName('Mtwara')]);
        District::create(['name' => 'Masasi Urban', 'region_id' => $this->getRegionByName('Mtwara')]);
        District::create(['name' => 'Mtwara', 'region_id' => $this->getRegionByName('Mtwara')]);
        District::create(['name' => 'Mtwara', 'region_id' => $this->getRegionByName('Mtwara')]);
        District::create(['name' => 'Nanyumbu', 'region_id' => $this->getRegionByName('Mtwara')]);
        District::create(['name' => 'Newala', 'region_id' => $this->getRegionByName('Mtwara')]);
        District::create(['name' => 'Tandahimba', 'region_id' => $this->getRegionByName('Mtwara')]);
        District::create(['name' => 'Ilemela', 'region_id' => $this->getRegionByName('Mwanza')]);
        District::create(['name' => 'Kwimba', 'region_id' => $this->getRegionByName('Mwanza')]);
        District::create(['name' => 'Magu', 'region_id' => $this->getRegionByName('Mwanza')]);
        District::create(['name' => 'Misungwi', 'region_id' => $this->getRegionByName('Mwanza')]);
        District::create(['name' => 'Nyamagana', 'region_id' => $this->getRegionByName('Mwanza')]);
        District::create(['name' => 'Sengerema', 'region_id' => $this->getRegionByName('Mwanza')]);
        District::create(['name' => 'Ukerewe', 'region_id' => $this->getRegionByName('Mwanza')]);
        District::create(['name' => 'Ludewa', 'region_id' => $this->getRegionByName('Njombe')]);
        District::create(['name' => 'Makambako', 'region_id' => $this->getRegionByName('Njombe')]);
        District::create(['name' => 'Makete', 'region_id' => $this->getRegionByName('Njombe')]);
        District::create(['name' => 'Njombe Rural', 'region_id' => $this->getRegionByName('Njombe')]);
        District::create(['name' => 'Njombe Urban', 'region_id' => $this->getRegionByName('Njombe')]);
        District::create(['name' => 'Wanging\'ombe', 'region_id' => $this->getRegionByName('Njombe')]);
        District::create(['name' => 'Bagamoyo', 'region_id' => $this->getRegionByName('Pwani')]);
        District::create(['name' => 'Kibaha Rural', 'region_id' => $this->getRegionByName('Pwani')]);
        District::create(['name' => 'Kibaha Urban', 'region_id' => $this->getRegionByName('Pwani')]);
        District::create(['name' => 'Kisarawe', 'region_id' => $this->getRegionByName('Pwani')]);
        District::create(['name' => 'Mafia', 'region_id' => $this->getRegionByName('Pwani')]);
        District::create(['name' => 'Mkuranga', 'region_id' => $this->getRegionByName('Pwani')]);
        District::create(['name' => 'Rufiji', 'region_id' => $this->getRegionByName('Pwani')]);
        District::create(['name' => 'Kalambo', 'region_id' => $this->getRegionByName('Rukwa')]);
        District::create(['name' => 'Nkasi', 'region_id' => $this->getRegionByName('Rukwa')]);
        District::create(['name' => 'Sumbawanga Rural', 'region_id' => $this->getRegionByName('Rukwa')]);
        District::create(['name' => 'Sumbawanga Urban', 'region_id' => $this->getRegionByName('Rukwa')]);
        District::create(['name' => 'Mbinga', 'region_id' => $this->getRegionByName('Ruvuma')]);
        District::create(['name' => 'Songea Rural', 'region_id' => $this->getRegionByName('Ruvuma')]);
        District::create(['name' => 'Songea Urban', 'region_id' => $this->getRegionByName('Ruvuma')]);
        District::create(['name' => 'Tunduru', 'region_id' => $this->getRegionByName('Ruvuma')]);
        District::create(['name' => 'Namtumbo', 'region_id' => $this->getRegionByName('Ruvuma')]);
        District::create(['name' => 'Nyasa', 'region_id' => $this->getRegionByName('Ruvuma')]);
        District::create(['name' => 'Kahama Urban', 'region_id' => $this->getRegionByName('Shinyanga')]);
        District::create(['name' => 'Kahama Rural', 'region_id' => $this->getRegionByName('Shinyanga')]);
        District::create(['name' => 'Kishapu', 'region_id' => $this->getRegionByName('Shinyanga')]);
        District::create(['name' => 'Shinyanga Rural', 'region_id' => $this->getRegionByName('Shinyanga')]);
        District::create(['name' => 'Shinyanga Urban', 'region_id' => $this->getRegionByName('Shinyanga')]);
        District::create(['name' => 'Bariadi', 'region_id' => $this->getRegionByName('Simiyu')]);
        District::create(['name' => 'Busega', 'region_id' => $this->getRegionByName('Simiyu')]);
        District::create(['name' => 'Itilima', 'region_id' => $this->getRegionByName('Simiyu')]);
        District::create(['name' => 'Maswa', 'region_id' => $this->getRegionByName('Simiyu')]);
        District::create(['name' => 'Meatu', 'region_id' => $this->getRegionByName('Simiyu')]);
        District::create(['name' => 'Ikungi', 'region_id' => $this->getRegionByName('Singida')]);
        District::create(['name' => 'Iramba', 'region_id' => $this->getRegionByName('Singida')]);
        District::create(['name' => 'Manyoni', 'region_id' => $this->getRegionByName('Singida')]);
        District::create(['name' => 'Mkalama', 'region_id' => $this->getRegionByName('Singida')]);
        District::create(['name' => 'Singida Rural', 'region_id' => $this->getRegionByName('Singida')]);
        District::create(['name' => 'Singida Urban', 'region_id' => $this->getRegionByName('Singida')]);
        District::create(['name' => 'Igunga', 'region_id' => $this->getRegionByName('Tabora')]);
        District::create(['name' => 'Kaliua', 'region_id' => $this->getRegionByName('Tabora')]);
        District::create(['name' => 'Nzega', 'region_id' => $this->getRegionByName('Tabora')]);
        District::create(['name' => 'Sikonge', 'region_id' => $this->getRegionByName('Tabora')]);
        District::create(['name' => 'Tabora', 'region_id' => $this->getRegionByName('Tabora')]);
        District::create(['name' => 'Urambo', 'region_id' => $this->getRegionByName('Tabora')]);
        District::create(['name' => 'Uyui', 'region_id' => $this->getRegionByName('Tabora')]);
        District::create(['name' => 'Handeni Rural', 'region_id' => $this->getRegionByName('Tanga')]);
        District::create(['name' => 'Handeni Urban', 'region_id' => $this->getRegionByName('Tanga')]);
        District::create(['name' => 'Kilindi', 'region_id' => $this->getRegionByName('Tanga')]);
        District::create(['name' => 'Korogwe Urban', 'region_id' => $this->getRegionByName('Tanga')]);
        District::create(['name' => 'Korogwe Rural', 'region_id' => $this->getRegionByName('Tanga')]);
        District::create(['name' => 'Lushoto', 'region_id' => $this->getRegionByName('Tanga')]);
        District::create(['name' => 'Muheza', 'region_id' => $this->getRegionByName('Tanga')]);
        District::create(['name' => 'Mkinga', 'region_id' => $this->getRegionByName('Tanga')]);
        District::create(['name' => 'Pangani', 'region_id' => $this->getRegionByName('Tanga')]);
        District::create(['name' => 'Tanga Urban', 'region_id' => $this->getRegionByName('Tanga')]);
    }

    private function getRegionByName($name) {
        $region = \App\Model\Region::where('name', $name)->first();
        return $region->id;
    }
}
