server {
    listen 443 ssl;
    server_name twiga.afyacall.co.tz;

    # SSL Certificates
    ssl_certificate /etc/nginx/ssl/twiga.afyacall.co.tz.crt;
    ssl_certificate_key /etc/nginx/ssl/twiga.afyacall.co.tz.key;

    root /var/www/html/public;
    index index.php index.html;

    # Routes
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM Settings
    location ~ \.php$ {
        fastcgi_pass afyacall:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
